firstArray = [
    'YUNG',
    'TE▲M',
    'LiL',
    'ヨフォシ–',
    'CVLT',
    'ṪHE',
    'عميق',
    'LIL',
    'SAMSUNG',
    'HD ',
    'シ',
    'ΔCID',
    '†Ɍïɭɭ',
    'TEEN',
    'dj',
    'вода',
    'звучи',
    'の男',
    '#RARE#',
    'TRΔP',
    'ΔQUA',
    '۞666',
    'DJ'
]

secondArray = [
    'L0RD',
    'W4ṪER',
    '㎒ ⦰⠁⡠',
    '.rar',
    '─╤╦︻ Pr0',
    'GURLZ',
    'TRA$H',
    'MANG',
    'F∀NGS',
    'UNIṪ',
    '.mp3',
    '•WINZIP',
    'SLVGS',
    'MOLLIWATER',
    'G∞gle',
    'BOI',
    'F00TB∀TH',
    '∞WAVE',
    '∞CHVRCH',
    'PVRP',
    'TEK',
    '韵律',
    '.biz',
    '420',
    ' W A K E',
    'CLOUDZ',
    'TATZ',
    'THUUG',
    'M00N',
    'CRYSTAL ۞',
    'SL1ME',
    '∞VIBEZ',
    'S§S',
    'CTRL',
    'سقى',
    'CH▲SE',
    'MANHΔTṪAN',
    'أضاف',
    'GVCCI',
    'UNIT',
    'SWΞG',
    'G0D',
    'CORE',
    'EYEZ',
    ' Ṫ▲C0BΞLL',
    'NETSC∀PE',
    ' M A C A '
]

thirdArray = [
    '†',
    '▲',
    '▩',
    '☥',
    '<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:2.5% 52.5%;background-size:4100%" title="yin_yang"></span></span>',
    '♛',
    '<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:7.5% 50%;background-size:4100%" title="v"></span></span>',
    'O0⦰',
    '∆',
    'iii',
    '▩',
    '▩',

    '▼▼',
    '##',
    ' // ',
    '±',
    '//◭//',
    '▽▽'
]

fourthArray = [
    'http://okfocus.s3.amazonaws.com/seapunkimages/vision3dae.jpg',
    'http://okfocus.s3.amazonaws.com/seapunkimages/br06_tropic_beach_by_71m3l3ss.jpg',
    'http://okfocus.s3.amazonaws.com/seapunkimages/beckbig.jpg',
    'http://okfocus.s3.amazonaws.com/seapunkimages/space.jpg',
    'http://okfocus.s3.amazonaws.com/seapunkimages/MtlCrs01.jpg',
    'http://okfocus.s3.amazonaws.com/seapunkimages/3dpyramid.jpg',
    'http://okfocus.s3.amazonaws.com/seapunkimages/Pyramid03.jpg'
]
